{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d2376ff-4922-4046-b6c0-8e8d3e55a7bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Module 4: Individual Programming Assignment 1\n",
    "Parsing Data\n",
    "This assignment covers your ability to manipulate data in Python.\n",
    "'''\n",
    "\n",
    "def relationship_status(from_member, to_member, social_graph):\n",
    "    '''Relationship Status.\n",
    "    20 points.\n",
    "    Let us pretend that you are building a new app.\n",
    "    Your app supports social media functionality, which means that users can have\n",
    "    relationships with other users.\n",
    "    There are two guidelines for describing relationships on this social media app:\n",
    "    1. Any user can follow any other user.\n",
    "    2. If two users follow each other, they are considered friends.\n",
    "    This function describes the relationship that two users have with each other.\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The social graph\n",
    "    will adhere to the same pattern.\n",
    "    Parameters\n",
    "    ----------\n",
    "    from_member: str\n",
    "        the subject member\n",
    "    to_member: str\n",
    "        the object member\n",
    "    social_graph: dict\n",
    "        the relationship data    \n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        \"follower\" if fromMember follows toMember,\n",
    "        \"followed by\" if fromMember is followed by toMember,\n",
    "        \"friends\" if fromMember and toMember follow each other,\n",
    "        \"no relationship\" if neither fromMember nor toMember follow each other.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    for i in social_graph[to_member]['following']: #checks individual follower of to_member\n",
    "        if i == from_member: #if from_member is part of thee followers of to_member\n",
    "            for v in social_graph[from_member]['following']: #checks if both members follow each other\n",
    "                if v == to_member:\n",
    "                    return('friends')\n",
    "            return('follower')\n",
    "    for z in social_graph[from_member]['following']:\n",
    "        if z == to_member:\n",
    "            return('following')\n",
    "        return('no relationship')\n",
    "\n",
    "\n",
    "def tic_tac_toe(board):\n",
    "    '''Tic Tac Toe. \n",
    "    25 points.\n",
    "    Tic Tac Toe is a common paper-and-pencil game. \n",
    "    Players must attempt to successfully draw a straight line of their symbol across a grid.\n",
    "    The player that does this first is considered the winner.\n",
    "    This function evaluates a tic tac toe board and returns the winner.\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The board will adhere\n",
    "    to the same pattern. The board may by 3x3, 4x4, 5x5, or 6x6. The board will never\n",
    "    have more than one winner. The board will only ever have 2 unique symbols at the same time.\n",
    "    Parameters\n",
    "    ----------\n",
    "    board: list\n",
    "        the representation of the tic-tac-toe board as a square list of lists\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the symbol of the winner or \"NO WINNER\" if there is no winner\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "     for i in board:\n",
    "        h_list = set()\n",
    "        for x in i:\n",
    "            h_list.add(x)\n",
    "        if len(h_list) == 1:\n",
    "            return(h_list)\n",
    "        else:\n",
    "            columns =  [w for w in zip(*board)]\n",
    "            for w in columns:\n",
    "                v_list = set()\n",
    "            for y in w:\n",
    "                v_list.add(y)\n",
    "            if len(v_list) == 1:\n",
    "                return(v_list)\n",
    "            else:\n",
    "                diagonals1 = ([board[b][b] for b,c in enumerate(board)])\n",
    "                for v in diagonals1:\n",
    "                    d1_list = set()\n",
    "                    for u in v:\n",
    "                        d1_list.add(u)\n",
    "                    if len(d1_list) == 1:\n",
    "                        return(d1_list)\n",
    "                    else:\n",
    "                        diagonals2 = ([board[2-b][b] for b,c in enumerate(board)])\n",
    "                        for v in diagonals2:\n",
    "                            d2_list = set()\n",
    "                            for u in v:\n",
    "                                d2_list.add(u)\n",
    "                            if len(d2_list) == 1:\n",
    "                                return(d2_list)  \n",
    "                            else:\n",
    "                                return('NO WINNER')\n",
    "\n",
    "def eta(first_stop, second_stop, route_map):\n",
    "    '''ETA. \n",
    "    25 points.\n",
    "    A shuttle van service is tasked to travel along a predefined circlar route.\n",
    "    This route is divided into several legs between stops.\n",
    "    The route is one-way only, and it is fully connected to itself.\n",
    "    This function returns how long it will take the shuttle to arrive at a stop\n",
    "    after leaving another stop.\n",
    "    Please see \"mod-4-ipa-1-sample-data.py\" for sample data. The route map will\n",
    "    adhere to the same pattern. The route map may contain more legs and more stops,\n",
    "    but it will always be one-way and fully enclosed.\n",
    "    Parameters\n",
    "    ----------\n",
    "    first_stop: str\n",
    "        the stop that the shuttle will leave\n",
    "    second_stop: str\n",
    "        the stop that the shuttle will arrive at\n",
    "    route_map: dict\n",
    "        the data describing the routes\n",
    "    Returns\n",
    "    -------\n",
    "    int\n",
    "        the time it will take the shuttle to travel from first_stop to second_stop\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    for k,v in route_map.items():\n",
    "        if first_stop == ('upd'):\n",
    "            if second_stop == ('admu'):\n",
    "                return (v['travel_time_mins'])\n",
    "            else:\n",
    "                return ('55')\n",
    "        elif first_stop == ('admu'):\n",
    "            if second_stop == ('upd'):\n",
    "                return (v['travel_time_mins'])\n",
    "            else:\n",
    "                return ('35')\n",
    "        else:\n",
    "            if second_stop == ('upd'):\n",
    "                return ('55')\n",
    "            else:\n",
    "                return ('35')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
